apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: jeffreyfreeland/my-python-app:v0.1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls: 
    - hosts:
      - my-app.test-test.com
  rules:
  - host: my-app.test-test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-app-service
          servicePort: 443
